#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title           : Statistics for Business Students # The title of the book. Will be placed in the left navbar.
author          : Asli Ogunc and Matt A. Wood # The author of the book
copyright       : "2025" # Copyright year to be placed in the footer
logo            : logo.png # A path to the book logo
# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints","*.png"]
# Auto-exclude files not in the toc
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: "auto" # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache: "" # A path to the jupyter cache that will be used to store execution artifacts. Defaults to `_build/.jupyter_cache/`
  exclude_patterns: [] # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)
  timeout: 100 # The maximum time (in seconds) each notebook cell is allowed to run.
  run_in_temp:
    false # If `True`, then a temporary directory will be created and used as the command working directory (cwd),
    # otherwise the notebook's parent directory will be the cwd.
  allow_errors: true # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.
  stderr_output: show # One of 'show', 'remove', 'remove-warn', 'warn', 'error', 'severe'

launch_buttons:
  colab_url: "https://colab.research.google.com"
  notebook_interface: "jupyterlab"
  binderhub_url: "https://mybinder.org"

# Information about where the book exists on the web
repository:
  url: https://github.com/mwood7/stats4business # Online location of your book
  # path_to_book: docs # Optional path to your book, relative to the repository root
  branch: main # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: "fav.ico"
  baseurl: https://mwood7.github.io/stats4business # The base URL where your book will be hosted.
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: false
  use_download_button: true
  home_page_in_navbar: true
  # thebe: true
  # google_analytics_id: G-XXXXXXX

sphinx:
  config:
    numfig: true
    html_math_sections: true
    # html_extra_path: ["CNAME", "robots.txt"]
    html_theme_options:
      use_download_button: true
      repository_url: https://github.com/mwood7/stats4business
      use_issues_button: true
      use_repository_button: true
      use_edit_page_button: true
      launch_buttons:
        {
          binderhub_url: "https://mybinder.org",
          colab_url: "https://colab.research.google.com",
        }
    bibtex_reference_style: author_year

# In Jupyter Book _config.yml

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    # - linkify
    # - replacements
    # - smartquotes
    # - substitution
    # - tasklist
    #- extension-1
    #- extension-2


# Define the name of the latex output file for PDF builds
# latex:
#   latex_documents:
#     targetname: book.tex

# sphinx:
#   extra_extensions:
#    # - sphinxcontrib.tikz
#    # - sphinx_exercise
#     - sphinx_inline_tabs



# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - book/references.bib
