name: Deploy Jupyter Book

on:
  push:
    branches:
      - main  # change if you use 'master' or another branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install jupyter-book ghp-import

      - name: Build the book
        run: |
          jupyter-book clean .
          jupyter-book build .

      - name: Deploy to GitHub Pages
        run: |
          ghp-import -n -p -f _build/html
